In [1]:
import numpy as np

In [2]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix_np = np.array(matrix)
print(matrix_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
matrix_np[0:1,0:2]

array([[1, 2]])

In [4]:
# Matriz 3x3
matrix_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("matrix_3x3:\n", matrix_3x3)
print("-" * 20)

matrix_3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------


In [5]:
matrix_3x3[2,0:2]

array([7, 8])

In [6]:
# Matriz 4x4
matrix_4x4 = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21],
    [22, 23, 24, 25]
])
print("matrix_4x4:\n", matrix_4x4)
print("-" * 20)


matrix_4x4:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------


In [7]:
matrix_4x4[1:3,1:3]

array([[15, 16],
       [19, 20]])

In [8]:
matrix_4x4[2:4,2:4]

array([[20, 21],
       [24, 25]])

In [9]:

# Matriz 5x3 (Ejemplo rectangular)
matrix_5x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])
print("matrix_5x3:\n", matrix_5x3)
print("-" * 20)

matrix_5x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
--------------------


In [10]:
matrix_5x3[1:-1,0:-1]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [11]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [12]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [13]:
print(arr)

[1. 2. 3. 4.]


In [14]:
arr = arr.astype(np.float64)
print(arr.dtype)
arr

float64


array([1., 2., 3., 4.])

In [15]:
arr = np.array([0, 1,2,3,4])
arr = arr.astype(np.bool_)

In [16]:
print(arr)

[False  True  True  True  True]


In [17]:
arr = np.array([0, 1,2,3,4])
arr = arr.astype(np.bytes_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [18]:
arr = np.array([0, '1','2','3','4',9])
arr = arr.astype(np.int8)
arr2 = arr*2
print(arr2)

[ 0  2  4  6  8 18]


In [19]:
array = np.array([
    [1,4,6],
    [9., 3, 2]
])
print(array.dtype)

float64


In [20]:
array = np.array([
    1,2,'hola',True
])
array.dtype

dtype('<U21')

In [21]:
valor = array[3]
print(valor)
print(type(valor))

True
<class 'numpy.str_'>


In [22]:
scalar = np.array(42)
print(scalar)

42


In [23]:
scalar.ndim

0

In [24]:
vector = np.array([1,2,3])
vector.ndim

1

In [26]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz.ndim

2